apiVersion: hub-of-hubs.open-cluster-management.io/v1
kind: HohHeartbeat
metadata:
  name: hub-of-hubs-heartbeat
  labels:
    name: hub-of-hubs-heartbeat
status:
  lastTimestamp: 1631964743
  conditions:
  - type: HohConditionAvailable
    status: Unknown
    lasttransitiontime: "2021-09-18T18:35:22.317563Z"
    reason: HohHeartbeatUpdateStopped
    message: HoH agent stopped updating its heartbeat.
